import type { ExpertProfile } from "@/lib/types";

/**
 * 12 mock expert directory profiles: accredited verifiers, consultants,
 * customs brokers and law firms. Verifier firms are real accreditation bodies;
 * named individuals/consultancies are illustrative.
 */
export const EXPERTS: ExpertProfile[] = [
  {
    id: "e1",
    name: "SGS — CBAM Verification Services",
    company: "SGS",
    profileType: "verifier",
    regimes: ["EU", "UK"],
    sectors: ["steel", "aluminium", "cement", "fertilizer", "hydrogen"],
    country: "Switzerland",
    accreditations: ["EN ISO 14065", "EMAS"],
    rating: 4.8,
    reviewCount: 42,
    enhancedListing: true,
    bio: "Global testing, inspection and certification body offering accredited CBAM emissions verification across all in-scope sectors, with installation-level MRV support.",
    reviews: [
      {
        author: "Markus Vogel",
        rating: 5,
        body: "Thorough installation audit; the methodology held up to NCA scrutiny first time.",
        date: "2026-05-12",
      },
      {
        author: "Priya Nair",
        rating: 5,
        body: "Helped our DRI-EAF mill move from defaults to verified actuals — big saving for our EU buyers.",
        date: "2026-04-20",
      },
    ],
  },
  {
    id: "e2",
    name: "Bureau Veritas — Carbon Assurance",
    company: "Bureau Veritas",
    profileType: "verifier",
    regimes: ["EU", "UK"],
    sectors: ["steel", "aluminium", "cement", "fertilizer"],
    country: "France",
    accreditations: ["EN ISO 14065"],
    rating: 4.7,
    reviewCount: 38,
    enhancedListing: true,
    bio: "Accredited third-party verifier providing annual CBAM verification, data-completeness review and calculation-methodology validation.",
    reviews: [
      {
        author: "Carlos Mendes",
        rating: 5,
        body: "Strong on aluminium indirect emissions — evidenced our PPA-backed power factor properly.",
        date: "2026-05-01",
      },
    ],
  },
  {
    id: "e3",
    name: "DNV — Emissions Verification",
    company: "DNV",
    profileType: "verifier",
    regimes: ["EU"],
    sectors: ["steel", "hydrogen", "electricity"],
    country: "Norway",
    accreditations: ["EN ISO 14065", "EMAS"],
    rating: 4.9,
    reviewCount: 51,
    enhancedListing: true,
    bio: "Independent assurance provider with deep energy-sector expertise, verifying embedded emissions for steel, hydrogen and electricity exporters.",
    reviews: [
      {
        author: "Elena Rossi",
        rating: 5,
        body: "Exceptional clarity on what evidence the verifier actually needs. Saved us weeks.",
        date: "2026-04-28",
      },
    ],
  },
  {
    id: "e4",
    name: "TÜV SÜD — CBAM Assurance",
    company: "TÜV SÜD",
    profileType: "verifier",
    regimes: ["EU", "UK"],
    sectors: ["steel", "aluminium", "cement"],
    country: "Germany",
    accreditations: ["EN ISO 14065"],
    rating: 4.6,
    reviewCount: 29,
    enhancedListing: false,
    bio: "Accredited verification of installation-level emissions data with a structured annual cycle aligned to CBAM reporting deadlines.",
    reviews: [],
  },
  {
    id: "e5",
    name: "Sofia Renaud",
    company: "Carbon Border Advisory",
    profileType: "consultant",
    regimes: ["EU", "UK"],
    sectors: ["steel", "aluminium", "fertilizer"],
    country: "Belgium",
    accreditations: ["CBAM Practitioner (self-declared)"],
    rating: 4.9,
    reviewCount: 33,
    enhancedListing: true,
    bio: "Independent CBAM consultant supporting importers through Authorised Declarant registration, certificate strategy and the default-vs-verified business case.",
    reviews: [
      {
        author: "Markus Vogel",
        rating: 5,
        body: "Saved us from over-buying certificates — explained the one-third sell-back cap before we made an expensive mistake.",
        date: "2026-05-15",
      },
      {
        author: "Tomasz Kowalski",
        rating: 5,
        body: "Sharp on policy nuance; always cites the primary source rather than guessing.",
        date: "2026-05-03",
      },
    ],
  },
  {
    id: "e6",
    name: "Rachel Adeyemi",
    company: "Thames Carbon Compliance",
    profileType: "consultant",
    regimes: ["UK", "EU"],
    sectors: ["steel", "cement", "fertilizer"],
    country: "United Kingdom",
    accreditations: ["UK CBAM Specialist (self-declared)"],
    rating: 4.8,
    reviewCount: 21,
    enhancedListing: true,
    bio: "UK-focused consultant preparing importers for the 1 January 2027 UK CBAM, including overseas-carbon-price credit evidencing and dual EU/UK compliance.",
    reviews: [
      {
        author: "James Whitfield",
        rating: 5,
        body: "The only adviser who clearly explained UK vs EU mechanism differences without overselling.",
        date: "2026-06-02",
      },
    ],
  },
  {
    id: "e7",
    name: "Dr. Anke Fischer",
    company: "Fischer Emissions Consulting",
    profileType: "consultant",
    regimes: ["EU"],
    sectors: ["steel", "aluminium"],
    country: "Germany",
    accreditations: ["Lead Verifier background"],
    rating: 4.7,
    reviewCount: 18,
    enhancedListing: false,
    bio: "Former lead verifier advising exporters on building MRV systems robust enough to support verified actuals at audit.",
    reviews: [
      {
        author: "Priya Nair",
        rating: 5,
        body: "Practical, no-nonsense guidance on getting installation data audit-ready.",
        date: "2026-05-20",
      },
    ],
  },
  {
    id: "e8",
    name: "Maersk Customs Services",
    company: "Maersk",
    profileType: "broker",
    regimes: ["EU", "UK"],
    sectors: ["steel", "aluminium", "cement", "fertilizer"],
    country: "Denmark",
    accreditations: ["AEO (Authorised Economic Operator)"],
    rating: 4.5,
    reviewCount: 47,
    enhancedListing: true,
    bio: "Customs brokerage integrating CBAM data capture into import declarations, with CN-code classification support to keep goods correctly in/out of scope.",
    reviews: [
      {
        author: "Elena Rossi",
        rating: 4,
        body: "Solid on classification; CBAM data flow integration is improving quickly.",
        date: "2026-05-09",
      },
    ],
  },
  {
    id: "e9",
    name: "Kuehne+Nagel — Trade Compliance",
    company: "Kuehne+Nagel",
    profileType: "broker",
    regimes: ["EU"],
    sectors: ["steel", "aluminium"],
    country: "Switzerland",
    accreditations: ["AEO"],
    rating: 4.4,
    reviewCount: 31,
    enhancedListing: false,
    bio: "Freight and customs partner offering CN-code validation against TARIC and CBAM reporting data assembly for importers.",
    reviews: [],
  },
  {
    id: "e10",
    name: "Clifford Chance — Environmental & Trade",
    company: "Clifford Chance",
    profileType: "law_firm",
    regimes: ["EU", "UK"],
    sectors: ["steel", "aluminium", "cement", "fertilizer", "hydrogen"],
    country: "United Kingdom",
    accreditations: ["Regulated legal practice"],
    rating: 4.9,
    reviewCount: 24,
    enhancedListing: true,
    bio: "International law firm advising on CBAM regulatory interpretation, penalty exposure, and cross-border carbon liability across EU and UK regimes.",
    reviews: [
      {
        author: "Tomasz Kowalski",
        rating: 5,
        body: "Authoritative on penalty exposure (3× shortfall) and criminal-liability risk framing.",
        date: "2026-05-18",
      },
    ],
  },
  {
    id: "e11",
    name: "Bird & Bird — Climate Regulation",
    company: "Bird & Bird",
    profileType: "law_firm",
    regimes: ["EU"],
    sectors: ["fertilizer", "hydrogen", "electricity"],
    country: "Germany",
    accreditations: ["Regulated legal practice"],
    rating: 4.7,
    reviewCount: 16,
    enhancedListing: false,
    bio: "Climate and energy regulatory practice advising on CBAM scope disputes, precursor-goods treatment and definitive-period methodology questions.",
    reviews: [],
  },
  {
    id: "e12",
    name: "ERM — Sustainability Consulting",
    company: "ERM",
    profileType: "consultant",
    regimes: ["EU", "UK"],
    sectors: ["cement", "fertilizer", "hydrogen"],
    country: "United Kingdom",
    accreditations: ["Sustainability advisory"],
    rating: 4.6,
    reviewCount: 27,
    enhancedListing: true,
    bio: "Global sustainability consultancy supporting large importers and exporters with carbon accounting, MRV design and multi-regime CBAM strategy.",
    reviews: [
      {
        author: "Carlos Mendes",
        rating: 5,
        body: "Helped us build a single MRV system serving both EU and UK obligations.",
        date: "2026-04-25",
      },
    ],
  },
];
