import type { ForumThread } from "@/lib/types";

/**
 * 20 realistic CBAM community threads across EU, UK and general channels.
 * Mock data only — no live forum yet.
 */
export const FORUM_THREADS: ForumThread[] = [
  {
    id: "t1",
    channel: "eu-importers",
    regime: "EU",
    title: "First annual declaration due 31 May — what does the surrender process actually look like?",
    authorName: "Markus Vogel",
    authorRole: "importer",
    replyCount: 14,
    upvotes: 27,
    expertEndorsed: true,
    lastActivity: "2026-06-04T09:12:00Z",
    preview:
      "We import BF-BOF steel coil from Turkey. This is our first definitive-period surrender. Walking through the registry steps — can anyone confirm the order: buy certs → hold 80% quarterly → surrender by 31 May?",
    replies: [
      {
        id: "t1r1",
        authorName: "Sofia Renaud",
        authorRole: "consultant",
        body: "Yes that's the right order. Key trap: the 80% holding is cumulative through each quarter, not per-import. And remember the sell-back cap is one third of certificates held — over-buying is unrecoverable.",
        upvotes: 19,
        createdAt: "2026-06-04T10:01:00Z",
        expertEndorsed: true,
      },
      {
        id: "t1r2",
        authorName: "Markus Vogel",
        authorRole: "importer",
        body: "That sell-back cap is exactly what bit a colleague. They bought a full year up front and couldn't unwind it.",
        upvotes: 6,
        createdAt: "2026-06-04T11:20:00Z",
        expertEndorsed: false,
      },
    ],
  },
  {
    id: "t2",
    channel: "eu-calculations",
    regime: "EU",
    title: "Default vs verified for DRI-EAF steel — is the gap really 30–55%?",
    authorName: "Priya Nair",
    authorRole: "exporter",
    replyCount: 22,
    upvotes: 41,
    expertEndorsed: true,
    lastActivity: "2026-06-03T16:45:00Z",
    preview:
      "Indian DRI-EAF mill here. Our verified actuals come in around 1.3 tCO2e/t but the EU default is ~2.05. That's a huge cost difference for our EU buyers. How hard is the verification to stand up?",
    replies: [
      {
        id: "t2r1",
        authorName: "Dr. Anke Fischer",
        authorRole: "verifier",
        body: "The gap is real because defaults sit around the 90th percentile of intensity — deliberately punitive. To claim 1.3 you need installation-level data, monitoring methodology, and an EN ISO 14065 accredited verifier signing off annually. Get your MRV in order first.",
        upvotes: 28,
        createdAt: "2026-06-03T17:30:00Z",
        expertEndorsed: true,
      },
    ],
  },
  {
    id: "t3",
    channel: "eu-policy",
    regime: "EU",
    title: "Omnibus simplification — did the mass-based de minimis actually land?",
    authorName: "Tomasz Kowalski",
    authorRole: "analyst",
    replyCount: 31,
    upvotes: 52,
    expertEndorsed: false,
    lastActivity: "2026-06-05T08:30:00Z",
    preview:
      "There was a proposed ~50t/yr mass-based exemption under the Omnibus package on top of the EUR 150/consignment de minimis. Has anyone confirmed the final text? Don't want to rely on a proposal.",
    replies: [
      {
        id: "t3r1",
        authorName: "Sofia Renaud",
        authorRole: "consultant",
        body: "Treat it as proposed until you see it in the Official Journal. The EUR 150/consignment threshold is established; the mass-based one was simplification-stage. Always check EUR-Lex for the consolidated text before advising a client.",
        upvotes: 24,
        createdAt: "2026-06-05T09:05:00Z",
        expertEndorsed: true,
      },
    ],
  },
  {
    id: "t4",
    channel: "eu-verifiers",
    regime: "EU",
    title: "Accreditation scope — EMAS vs EN ISO 14065 for CBAM verification",
    authorName: "Dr. Anke Fischer",
    authorRole: "verifier",
    replyCount: 9,
    upvotes: 18,
    expertEndorsed: true,
    lastActivity: "2026-06-02T13:00:00Z",
    preview:
      "Clarifying for newer verifiers: both EN ISO 14065 and EMAS routes are recognised. Scope matters — your accreditation must cover the relevant activity group for the installation's sector.",
    replies: [],
  },
  {
    id: "t5",
    channel: "eu-exporters",
    regime: "EU",
    title: "Aluminium primary — indirect (electricity) emissions are killing our number",
    authorName: "Carlos Mendes",
    authorRole: "exporter",
    replyCount: 17,
    upvotes: 33,
    expertEndorsed: false,
    lastActivity: "2026-06-01T11:15:00Z",
    preview:
      "Primary aluminium default is ~16–18 tCO2e/t and most of it is the grid factor. If we can prove a cleaner power mix, how much can the verified indirect portion actually move?",
    replies: [
      {
        id: "t5r1",
        authorName: "Sofia Renaud",
        authorRole: "consultant",
        body: "For aluminium both direct and indirect count. A genuinely low-carbon PPA-backed power supply can move you toward the 12–15 range, but you must evidence the actual grid/contract factor, not a national average.",
        upvotes: 21,
        createdAt: "2026-06-01T12:40:00Z",
        expertEndorsed: true,
      },
    ],
  },
  {
    id: "t6",
    channel: "eu-importers",
    regime: "EU",
    title: "Authorised CBAM Declarant status — how long is the NCA taking?",
    authorName: "Elena Rossi",
    authorRole: "importer",
    replyCount: 12,
    upvotes: 20,
    expertEndorsed: false,
    lastActivity: "2026-05-30T15:20:00Z",
    preview:
      "You must be an Authorised CBAM Declarant before your first definitive-period import. What lead times are people seeing from their National Competent Authority?",
    replies: [],
  },
  {
    id: "t7",
    channel: "eu-calculations",
    regime: "EU",
    title: "Precursor goods — tracking embedded emissions of input ammonia for urea",
    authorName: "Priya Nair",
    authorRole: "exporter",
    replyCount: 8,
    upvotes: 15,
    expertEndorsed: true,
    lastActivity: "2026-05-29T10:00:00Z",
    preview:
      "For urea the N2O from nitric acid and the ammonia feedstock dominate. How granular does the precursor tracking need to be for the embedded emissions to be accepted?",
    replies: [],
  },
  {
    id: "t8",
    channel: "eu-policy",
    regime: "EU",
    title: "Certificate price tracking the weekly ETS average — practical hedging?",
    authorName: "Tomasz Kowalski",
    authorRole: "analyst",
    replyCount: 19,
    upvotes: 29,
    expertEndorsed: false,
    lastActivity: "2026-05-28T14:30:00Z",
    preview:
      "Cert price = weekly average EU ETS auction price (~EUR 50–70, has topped EUR 100). With the 1/3 sell-back cap, how are larger importers managing price risk without over-buying?",
    replies: [],
  },
  {
    id: "t9",
    channel: "uk-importers",
    regime: "UK",
    title: "UK CBAM live 1 Jan 2027 — GBP 50k threshold, how is it measured?",
    authorName: "James Whitfield",
    authorRole: "importer",
    replyCount: 16,
    upvotes: 34,
    expertEndorsed: true,
    lastActivity: "2026-06-04T17:00:00Z",
    preview:
      "UK entry threshold is GBP 50,000 of CBAM goods over any rolling 12-month period. Is that per-importer across all sectors combined, or per commodity?",
    replies: [
      {
        id: "t9r1",
        authorName: "Rachel Adeyemi",
        authorRole: "consultant",
        body: "It's the value of in-scope CBAM goods over a rolling 12 months. Note the UK scope excludes electricity, unlike the EU. And the mechanism is a direct levy referencing the UK carbon price — no certificates.",
        upvotes: 22,
        createdAt: "2026-06-04T18:15:00Z",
        expertEndorsed: true,
      },
    ],
  },
  {
    id: "t10",
    channel: "uk-policy",
    regime: "UK",
    title: "Credit for overseas carbon price already paid — evidencing it to HMRC",
    authorName: "Rachel Adeyemi",
    authorRole: "consultant",
    replyCount: 11,
    upvotes: 25,
    expertEndorsed: true,
    lastActivity: "2026-06-03T09:45:00Z",
    preview:
      "The UK levy credits any overseas carbon price already paid. For exporters from countries with a real ETS this matters a lot. What documentation is HMRC expected to require?",
    replies: [],
  },
  {
    id: "t11",
    channel: "uk-importers",
    regime: "UK",
    title: "UK vs EU — running both regimes for the same steel shipments",
    authorName: "James Whitfield",
    authorRole: "importer",
    replyCount: 13,
    upvotes: 27,
    expertEndorsed: false,
    lastActivity: "2026-06-02T16:10:00Z",
    preview:
      "We sell the same steel into both the EU and UK. Two different mechanisms (certificates vs levy), two calendars (31 May annual vs accounting periods). How are people structuring compliance to avoid double work?",
    replies: [],
  },
  {
    id: "t12",
    channel: "uk-policy",
    regime: "UK",
    title: "HMRC guidance updates — where to monitor for the definitive ruleset",
    authorName: "Rachel Adeyemi",
    authorRole: "consultant",
    replyCount: 7,
    upvotes: 14,
    expertEndorsed: false,
    lastActivity: "2026-05-31T12:00:00Z",
    preview:
      "Best primary sources to watch for UK CBAM as we approach 2027: GOV.UK/HMRC guidance pages and the legislation itself. Anyone tracking a consolidated changelog?",
    replies: [],
  },
  {
    id: "t13",
    channel: "announcements",
    regime: "GLOBAL",
    title: "Welcome to CarbonGate — verified members only",
    authorName: "CarbonGate Team",
    authorRole: "admin",
    replyCount: 5,
    upvotes: 88,
    expertEndorsed: true,
    lastActivity: "2026-06-05T07:00:00Z",
    preview:
      "This is a gated community of verified carbon-border professionals. Channels are regime-tagged. The AI assistant answers only from a curated, citable corpus and refuses to guess.",
    replies: [],
  },
  {
    id: "t14",
    channel: "introductions",
    regime: "GLOBAL",
    title: "Intro: ESG analyst covering steel & aluminium supply chains",
    authorName: "Tomasz Kowalski",
    authorRole: "analyst",
    replyCount: 9,
    upvotes: 17,
    expertEndorsed: false,
    lastActivity: "2026-06-04T13:30:00Z",
    preview:
      "Hi all — I cover carbon exposure across EU/UK importers' supply chains. Here to benchmark default-vs-verified intensity and track the cross-regime picture.",
    replies: [],
  },
  {
    id: "t15",
    channel: "tools-resources",
    regime: "GLOBAL",
    title: "Deterministic calculator vs spreadsheet — why the engine matters",
    authorName: "Sofia Renaud",
    authorRole: "consultant",
    replyCount: 10,
    upvotes: 23,
    expertEndorsed: true,
    lastActivity: "2026-06-03T15:00:00Z",
    preview:
      "A reminder for clients: the platform's calculator is deterministic — same inputs, same numbers, methodology shown. Never let an AI 'estimate' a certificate cost; route it to the engine.",
    replies: [],
  },
  {
    id: "t16",
    channel: "tools-resources",
    regime: "GLOBAL",
    title: "Template library — quarterly declaration worksheet feedback wanted",
    authorName: "Elena Rossi",
    authorRole: "importer",
    replyCount: 6,
    upvotes: 12,
    expertEndorsed: false,
    lastActivity: "2026-06-01T10:30:00Z",
    preview:
      "Trialling the quarterly declaration template. Would value input on how others structure the cumulative-emissions running total for the 80% holding check.",
    replies: [],
  },
  {
    id: "t17",
    channel: "eu-importers",
    regime: "EU",
    title: "Penalty exposure — 3× certificate price per tonne of shortfall",
    authorName: "Markus Vogel",
    authorRole: "importer",
    replyCount: 15,
    upvotes: 31,
    expertEndorsed: true,
    lastActivity: "2026-05-30T09:00:00Z",
    preview:
      "Just internalising the penalty maths: shortfall is charged at 3× the certificate price per tonne, plus potential criminal liability. That reframes the cost of getting the embedded-emissions number wrong.",
    replies: [],
  },
  {
    id: "t18",
    channel: "eu-exporters",
    regime: "EU",
    title: "Scrap-EAF route — biggest default-vs-verified saving of any steel route?",
    authorName: "Carlos Mendes",
    authorRole: "exporter",
    replyCount: 12,
    upvotes: 26,
    expertEndorsed: false,
    lastActivity: "2026-05-29T14:00:00Z",
    preview:
      "Scrap-EAF default is ~0.9–1.4 and good actuals can be 0.4–0.8 — that's 40–60% savings. For high-recycled-content producers this is the strongest verification business case.",
    replies: [],
  },
  {
    id: "t19",
    channel: "eu-calculations",
    regime: "EU",
    title: "CN code classification driving scope — getting it wrong is expensive",
    authorName: "Priya Nair",
    authorRole: "exporter",
    replyCount: 8,
    upvotes: 19,
    expertEndorsed: true,
    lastActivity: "2026-05-27T11:00:00Z",
    preview:
      "The CN code determines whether goods are in scope and which rules apply. Misclassification cascades into the whole obligation. How are people validating CN codes against TARIC up front?",
    replies: [],
  },
  {
    id: "t20",
    channel: "announcements",
    regime: "GLOBAL",
    title: "Corpus update cadence — nothing is auto-published without human review",
    authorName: "CarbonGate Team",
    authorRole: "admin",
    replyCount: 4,
    upvotes: 35,
    expertEndorsed: true,
    lastActivity: "2026-06-05T06:30:00Z",
    preview:
      "Our data-freshness pipeline detects changes fast but stages them for expert review (1–5 business days) before publishing. Every answer and document carries an 'as of' date. That discipline is the product.",
    replies: [],
  },
];

/** Channel registry, grouped for the sidebar. */
export const CHANNELS = {
  EU: [
    { slug: "eu-importers", label: "#eu-importers", regime: "EU" as const },
    { slug: "eu-exporters", label: "#eu-exporters", regime: "EU" as const },
    { slug: "eu-verifiers", label: "#eu-verifiers", regime: "EU" as const },
    { slug: "eu-calculations", label: "#eu-calculations", regime: "EU" as const },
    { slug: "eu-policy", label: "#eu-policy", regime: "EU" as const },
  ],
  UK: [
    { slug: "uk-importers", label: "#uk-importers", regime: "UK" as const },
    { slug: "uk-policy", label: "#uk-policy", regime: "UK" as const },
  ],
  General: [
    { slug: "announcements", label: "#announcements", regime: "GLOBAL" as const },
    { slug: "introductions", label: "#introductions", regime: "GLOBAL" as const },
    { slug: "tools-resources", label: "#tools-resources", regime: "GLOBAL" as const },
  ],
};
